version: '3'
services:
  main:
    build: .
    volumes:
      - ./data:/nycs/data
    environment:
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    command: ["python3", "nycs/core/run.py"]

  tests:
    build: .
    environment:
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
    command: ["pytest", "nycs/tests"]

